config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :services do
    resources :activity_slots, only: :create
  end
  resources :activity_slots, only: [:edit, :update, :destroy]

  scope '(:locale)', locale: /fr/ do
    root to: 'pages#home'
    resources :services do
      resources :activity_slots, only: :create
    end
    resources :activity_slots, only: [:edit, :update, :destroy]  end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  belongs_to :ngo, required: true
  has_many :activity_slots, dependent: :delete_all
  has_many :categories, through: :activity_slots
  has_many :beneficiaries, through: :activity_slots
  geocoded_by :address
  validates :name, presence: true
  validates :address, presence: true, uniqueness: { notice: "An Access Point already exists at this address / Un Point d'Accès existe déjà à cette adresse" }
  accepts_nested_attributes_for :activity_slots


  after_validation :geocode, if: :will_save_change_to_address?
  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

  def self.search(catids, location, distance)
    if (location.present? && distance.present?)
      all_coords = Geocoder.search(location)
      coords = all_coords.first.coordinates
      @results = Service.within(distance.to_i, origin: coords) if coords
    else
      @results = Service.all
    end
    if catids
      catids.map!(&:to_i)
      @results = @results.select{|service| (service.category_ids & catids).any?}
    end
    return @results
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :show

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @activity_slot = ActivitySlot.new
  end

  # GET /services/new
  def new
    @categories = Category.all
    @service = Service.new
    authorize @service
    @service.activity_slots.build
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.user = current_user
    authorize @service
    respond_to do |format|
      if @service.save
        params[:service][:activity_slots_attributes]["0"][:category_ids].delete("")
        if params[:service][:activity_slots_attributes]["0"][:category_ids].any?
          binding.pry
          create_categories(params[:service][:activity_slots_attributes]["0"][:category_ids], params[:service][:activity_slots_attributes]["0"])
        end
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        Rails.logger.info(@service.errors.inspect)
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
      authorize @service
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :address, :phone, :comment, :mail, :link, :ngo_id, activity_slots_attributes: [:id, :title, :opening_hours, :activities, :price, :appointment, :start_date, :end_date])
    end

    def create_categories(catids, activity_slot)
      catids.each do |catid|
        activityCat = ActivityCategory.new
        activityCat.activity_slot = @service.activity_slots[0]
        activityCat.category = Category.find(catid.to_i)
        activityCat.save!
      end
    end
end

app/views/services/_form.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="service-form">
        <div class="mt-3">
          <%= simple_form_for(@service) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="form-group">
              <%= f.association :ngo, input_html: { required: true }  %>
            </div>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: t('.name_placeholder'), class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control', id: "search-location" %>
            </div>
            <div class="form-group">
              <%= f.label :comment %>
              <%= f.text_area :comment, rows: 5, class: 'form-control' %>
            </div>
            <div class="mt-3">
              <%= f.submit class: 'btn btn-warning' %>
              <%= link_to 'Cancel', services_path, class: 'btn btn-primary ml-2' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

app/views/services/index.html.erb
<div class="container">
  <div class="new-service-div">
    <%= link_to t('.new_service'), new_service_path, class: "btn btn-warning btn-new-service" %>
  </div>
  <h1 class="title-services"><%= t('.all_services') %></h1>

  <div class="row">
      <% @services.each do |service| %>
        <%= render partial: 'components/service_card_admin', locals: { service: service } %>
      <% end %>
  </div>
</div>

app/views/services/new.html.erb
<h1><%= t('.new_service') %></h1>

<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="service-form">
        <div class="mt-3">
          <%= simple_form_for(@service) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="form-group">
              <%= f.association :ngo, input_html: { required: true }  %>
            </div>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: t('.name_placeholder'), class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, class: 'form-control', id: "search-location" %>
            </div>
            <div class="form-group">
              <%= f.label :comment %>
              <%= f.text_area :comment, rows: 5, class: 'form-control' %>
            </div>
            <div class="nested-form-for-activities">
              <h4><%= t('.new_program') %></h4>
              <i><%= t('.can_add_later') %></i>
              <ul>
              <%= f.nested_fields_for :activity_slots do |activity_slots_form| %>
                <li>
                  <%= activity_slots_form.input :title, placeholder: "Title"%>
                  <%= activity_slots_form.input :opening_hours, placeholder: "Opening Hours"%>
                  <%= activity_slots_form.association :categories, as: :check_boxes, item_wrapper_tag: :div, item_wrapper_class: "checkbox-inline"  %>
                  <%= activity_slots_form.input :price, placeholder: "Price"%>
                </li>
              <% end %>
              </ul>
            </div>
            <div class="mt-3">
              <%= f.submit class: 'btn btn-warning' %>
              <%= link_to 'Cancel', services_path, class: 'btn btn-primary ml-2' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="container show-service">
    <%= link_to t('.back_to_access_points'), services_path, class: "btn btn-primary back-btn" %>
    <div class="access-point">
    <div class="ap-title">
        <img src="<%= @service.ngo.logo %>" alt="logo" height="42"/><h3><%= @service.name %></h3>
    </div>
    <i><%= @service.ngo.name %></i>
    <p><%= @service.address %></p>
    <p><%= @service.phone %></p>
    <p><%= @service.mail %></p>
    <p><%= @service.link %></p>
    <p><%= @service.comment %></p>
    <% if policy(@service).edit? %>
      <%= link_to 'Edit', edit_service_path(@service) %>
    <% end %>
  </div>
  <% if @service.activity_slots.any? %>
    <%= render 'components/activity_card', service: @service %>
  <% else %>
    <%= t('.no_activity') %>
  <% end %>
  <% if policy(@service).edit? %>
    <div class="new-activity">
      <h4><%= t('.new_activity') %></h4>
      <%= render 'activity_slots/form', service: @service, activity_slot: @activity_slot %>
      <br>
    </div>
  <% end %>
  <br>
</div>