config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :services do
    resources :activity_slots, only: :create
  end
  resources :activity_slots, only: [:edit, :update, :destroy]

  scope '(:locale)', locale: /fr/ do
    root to: 'pages#home'
    resources :services do
      resources :activity_slots, only: :create
    end
    resources :activity_slots, only: [:edit, :update, :destroy]  end
end

app/models/activity_slot.rb
class ActivitySlot < ApplicationRecord
  has_many :activity_beneficiaries, dependent: :delete_all
  has_many :beneficiaries, through: :activity_beneficiaries
  accepts_nested_attributes_for :beneficiaries
  has_many :activity_categories, dependent: :delete_all
  has_many :categories, through: :activity_categories
  accepts_nested_attributes_for :categories
  belongs_to :service
end

app/views/pages/_map_box.html.erb
<div>
  <p><strong><%= service.name %></strong></p>
  <%= service.phone %> <br>
  <%= service.comment %>
  </%>
</div>

app/views/pages/home.html.erb
<script>
  function printContent(el){
    var restorepage = $('body').html();
    $('.' + el).remove();
    window.print();
    $('body').empty();
    $('body').html(restorepage);
  }
</script>


<div class="container">
  <div class="row">
    <ul class="lang-switcher removeForPrint lang-switcher--pill">
        <li><a href="<%= root_path(locale: :en) %>" class="<%= "is-active" if I18n.locale != :fr %>">En</a></li>
        <li><a href="<%= root_path(locale: :fr) %>" class="<%= "is-active" if I18n.locale == :fr %>">Fr</a></li>
    </ul>

    <h1 class="removeForPrint">SoliMap</h1>
  	<div class="col-xs-12 col-md-8" id="map" class="printMe2" data-markers="<%= @markers.to_json %>">

    </div>
    <div class="col-xs-12 col-md-4 removeForPrint" >
      <%= form_tag(root_path, method: :get) do %>
      <h4><%= t('.location') %></h4>
        <div class="searchbar paddingbottom">
          <%= t('.services_within') %>  <%= select_tag "distance", "<option>1</option><option selected='selected'>5</option><option>10</option>".html_safe %> kms <%= t('.from') %>
        </div>
        <div class="searchbar">
          <%= text_field_tag 'location', nil, placeholder: params[:location], id: "search-location" %>
        </div>
      <h4><%= t('.categories') %></h4>
        <ul class="filter-list">
          <% @categories.each do |category| %>
            <li>
              <label class="category-option btn btn-chore btn-small btn-block" id="label-<%= category.id %>" for="<%= category.id %>">
                 <%= check_box_tag "category_ids[]", category.id, @catids_selected.include?(category.id), id: category.id, class: "category-checkbox", style: 'visibility: hidden' %>
                 <%= render partial: 'components/category_card', locals: { category: category } %>
              </label>
            </li>
          <% end %>
        </ul>
      <div class="submit-search-container">
        <%= submit_tag(t('.filter'), class: "btn btn-search btn-primary") %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row col-xs-12 col-md-8 container printMe" id="div-results">
    <div class="flexbox">
      <button id="print" class="removeForPrint btn btn-print btn-success" onclick="printContent('removeForPrint');" ><%= t('.print') %></button>
      <h4 class="result-title">
        <% if (@services.empty?) %>
          <%= t('.no_results') %>
        <% elsif (params[:location].present?&&params[:distance].present?) %>
        <%= t('.results_within', distance: params[:distance], location: params[:location]) %>
        <% else %>
        <%= t('.results') %>
        <% end %>
        </h4>
    </div>

    <% @services.each do |service| %>
      <%= render partial: 'components/service_card', locals: { service: service } %>
    <% end %>
  </div>

<!--   <div class="row col-xs-12 col-md-8 container card-presentation">
    <div>
      <h4 class="result-title">Results</h4>
    </div>
    <div>

      <%# @params[:category_ids].each do |category_id| %>
        <button class="category-list active btn btn-chore btn-small btn-block" type="button" data-toggle="collapse" data-target="#collapse<%#= category_id %>" aria-expanded="false" aria-controls="collapse<%#= category_id %>">
            <%#= cl_image_tag Category.find(category_id).icon, height: 25, class: "category-icon" %>
            <span class="category-name">
              <%#= Category.find(category_id).name %>
            </span>
        </button>
        <div class="collapse in" id="collapse<%#= category_id %>">
            <%# @services.where(category: category).each do |service| %>
              <%#= render partial: 'components/service_card', locals: { service: service } %>
            <%# end %>
        </div>
      <%# end %>

    </div>
  </div> -->
</div>