config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :services do
    resources :activity_slots, only: :create
  end
  resources :activity_slots, only: [:edit, :update, :destroy]

  scope '(:locale)', locale: /fr/ do
    root to: 'pages#home'
    resources :services do
      resources :activity_slots, only: :create
    end
    resources :activity_slots, only: [:edit, :update, :destroy]  end
end

app/models/activity_slot.rb
class ActivitySlot < ApplicationRecord
  has_many :activity_beneficiaries, dependent: :delete_all
  has_many :beneficiaries, through: :activity_beneficiaries
  accepts_nested_attributes_for :beneficiaries
  has_many :activity_categories, dependent: :delete_all
  has_many :categories, through: :activity_categories
  accepts_nested_attributes_for :categories
  belongs_to :service
end

app/controllers/activity_slots_controller.rb
class ActivitySlotsController < ApplicationController
  before_action :set_activity_slot, only: [:show, :edit, :update, :destroy]

  # GET /activity_slots
  # GET /activity_slots.json
  def index
    @activity_slots = ActivitySlot.all
  end

  # GET /activity_slots/1
  # GET /activity_slots/1.json
  def show
  end

  # GET /activity_slots/new
  def new
    @activity_slot = ActivitySlot.new
  end

  # GET /activity_slots/1/edit
  def edit
  end

  # POST /activity_slots
  # POST /activity_slots.json
  def create
    @service = Service.find(params[:service_id])
    @activity_slot = ActivitySlot.new(activity_slot_params)
    @activity_slot.service = @service
    authorize @activity_slot
    if @activity_slot.save
      params[:activity_slot][:category_ids].delete("")
      if params[:activity_slot][:category_ids].any?
        create_categories(params[:activity_slot][:category_ids])
      end
      redirect_to service_path(@service)
    else
      render 'services/show'
    end
  end

  # PATCH/PUT /activity_slots/1
  # PATCH/PUT /activity_slots/1.json
  def update
    respond_to do |format|
      if @activity_slot.update(activity_slot_params)
        params[:activity_slot][:category_ids].delete("")
        if params[:activity_slot][:category_ids].any?
          create_categories(params[:activity_slot][:category_ids])
        end
        format.html { redirect_to services_path, notice: 'Activity slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_slot }
      else
        format.html { render :edit }
        format.json { render json: @activity_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_slots/1
  # DELETE /activity_slots/1.json
  def destroy
    @activity_slot.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Activity slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_slot
      @activity_slot = ActivitySlot.find(params[:id])
      authorize @activity_slot
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_slot_params
      params.require(:activity_slot).permit(:title, :opening_hours, :activities, :price, :appointment, :start_date, :end_date)
    end

    def create_categories(catids)
      @activity_slot.categories.destroy_all
      catids.each do |catid|
        activityCat = ActivityCategory.new
        activityCat.activity_slot = @activity_slot
        activityCat.category = Category.find(catid.to_i)
        activityCat.save!
      end
    end
end

app/views/activity_slots/_edit_form.html.erb
<div class="container">
  <%= simple_form_for(activity_slot) do |f| %>
    <%= f.input :title, placeholder: "Title"%>
    <%= f.input :opening_hours, placeholder: "Opening Hours"%>
    <%= f.association :categories, as: :check_boxes, item_wrapper_tag: :div, item_wrapper_class: "checkbox-inline"  %>
    <%= f.input :price, placeholder: "Price"%>
    <%= f.submit class: "btn btn-warning" %>   <%= link_to 'Cancel', services_path, class: 'btn btn-primary ml-2' %>
  <% end %>

</div>

app/views/activity_slots/_form.html.erb
<% (service = activity_slot.service) unless activity_slot.service.nil? %>
<%= simple_form_for ([service, activity_slot]) do |f| %>
  <%= f.input :title, placeholder: "Title"%>
  <%= f.input :opening_hours, placeholder: "Opening Hours"%>
  <%= f.association :categories, as: :check_boxes, item_wrapper_tag: :div, item_wrapper_class: "checkbox-inline"  %>
  <%= f.input :price, placeholder: "Price"%>
  <%= f.submit class: "btn btn-warning" %>
<% end %>

app/views/activity_slots/_show.html.erb
<p id="notice"><%= notice %></p>
<div class="activity">
  <%= t('.activity_title') %>: <%= activity_slot.title %> <br>
  <%= t('.activity_hours') %>: <%= activity_slot.opening_hours %> <br>
  <%= t('.activity_price') %>: <%= activity_slot.price %> <br>
  <%= link_to 'Edit', edit_activity_slot_path(activity_slot) %> |
  <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, activity_slot, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/activity_slots/edit.html.erb
<h1>Editing Activity Slot</h1>

<%= render 'edit_form', activity_slot: @activity_slot %>

app/views/activity_slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activity Slots</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_slots.each do |activity_slot| %>
      <tr>
        <td><%= link_to 'Show', activity_slot %></td>
        <td><%= link_to 'Edit', edit_activity_slot_path(activity_slot) %></td>
        <td><%= link_to 'Destroy', activity_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity Slot', new_activity_slot_path %>

app/views/activity_slots/new.html.erb
<h1>New Activity Slot</h1>

<%#= render 'form', activity_slot: @activity_slot %>

<%#= link_to 'Back', service_path %>